name: CD Windows (vcpkg + MSVC)

on:
  push:
    tags:
      - 'v*'

env:
  USERNAME: ${{ github.repository_owner }}
  FEED_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json,readwrite"

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 70

    permissions:
      packages: write
      contents: write

    steps:
      # ====================================================================
      # Checkout
      # ====================================================================
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # ====================================================================
      # Setup Qt
      # ====================================================================
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
         version: '6.10.2'
         target: 'desktop'
         arch: 'win64_msvc2022_64'
         modules: 'qtshadertools'

      # ====================================================================
      # Setup vcpkg
      # ====================================================================
      - name: Setup vcpkg (latest)
        run: |
          cd C:\vcpkg

          Write-Host "Fetching specific baseline..."
          git fetch origin cd61e1e26a038e82d6550a3ebbe0fbbfe7da78e3
          
          Write-Host "Checking out project baseline..."
          git checkout cd61e1e26a038e82d6550a3ebbe0fbbfe7da78e3
          
          Write-Host "Bootstrapping vcpkg..."
          .\bootstrap-vcpkg.bat

          Write-Host "Setting environment variables..."
          echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV
          echo "C:\vcpkg" >> $env:GITHUB_PATH

      # ====================================================================
      # Configuration of NuGet source for vcpkg cache
      # ====================================================================
      - name: Configure NuGet source for vcpkg cache
        shell: pwsh
        env:
            FEED_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          $nugetExe = & "$env:VCPKG_ROOT\vcpkg.exe" fetch nuget | Select-Object -Last 1
          Write-Host "Using NuGet executable: $nugetExe"
          
          & $nugetExe sources add `
            -Source "$env:FEED_URL" `
            -StorePasswordInClearText `
            -Name "GitHubPackages" `
            -UserName "$env:USERNAME" `
            -Password "${{ secrets.GITHUB_TOKEN }}"

          & $nugetExe setapikey "${{ secrets.GITHUB_TOKEN }}" -Source "$env:FEED_URL"

      # ====================================================================
      # Setup Python and install Halide via pip
      # ====================================================================
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
  
      - name: pip halide
        run: |
         pip install --only-binary :all: halide==21.0.0
         echo "HALIDE_CMAKE_DIR=$(python3 -c 'import halide; print(halide.cmake_dir())')" >> "$GITHUB_ENV"
    
      # ====================================================================
      # Configure & Build with CMake
      # ====================================================================
      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'release-vcpkg-msvc'
          configurePresetAdditionalArgs: "['-Ddesktop_ui=ON','-Dtests=OFF']"
          buildPreset: 'release-vcpkg-msvc'
          buildPresetAdditionalArgs: "['--config Release']"

      # ====================================================================
      # Packaging Release Artifact
      # ====================================================================
      - name: Package NSIS Installer
        shell: pwsh
        run: |
          # 1. Gather Qt dependencies next to the executable
          $exePath = "build/release-vcpkg-msvc/Release/capturemoment_desktop.exe"

          $halideBin = Join-Path (Split-Path $env:HALIDE_CMAKE_DIR -Parent) "bin"
          if (Test-Path "$halideBin\Halide.dll") {
              Copy-Item "$halideBin\Halide.dll" "build\release-vcpkg-msvc\Release\" -Force
              Write-Host "Halide.dll copied successfully."
          } else {
              Write-Error "Halide.dll not found in $halideBin"
              exit 1
          }

          & "C:\Qt\6.10.2\msvc2022_64\bin\windeployqt.exe" "$exePath" --release --no-translations
          
          # 2. Run CPack to build the NSIS installer
          cpack --build-config Release --config build/release-vcpkg-msvc/CPackConfig.cmake

      - name: Upload Installer to Release
        uses: softprops/action-gh-release@v2
        with:
          # CPack usually names NSIS files like ProjectName-Version-win64.exe
          files: build/CaptureMoment-*-win64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

